# File: prometheus/prometheus.yml

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nexus-orchestrator'
    static_configs:
      - targets: ['nexus.orchestrator:9091'] # docker-compose 서비스 이름을 사용

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 