services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  supabase:
    image: postgres:15-alpine
    container_name: supabase_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "postgres"

  nexus.scheduler:
    image: ${DOCKER_REGISTRY-}nexusscheduler
    build:
      context: .
      dockerfile: Nexus.Scheduler/Dockerfile
    container_name: nexus_scheduler
    depends_on:
      - redis
    ports:
      - "9091:9091"
    volumes:
      - ./data:/app/data

  nexus.integrator:
    image: ${DOCKER_REGISTRY-}nexusintegrator
    build:
      context: .
      dockerfile: Nexus.Integrator/Dockerfile
    container_name: nexus_integrator
    depends_on:
      - redis
    ports:
      - "9092:9092"

  nexus.ui:
    image: ${DOCKER_REGISTRY-}nexusui
    build:
      context: .
      dockerfile: Nexus.UI/Dockerfile
    container_name: nexus_ui
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      # - nexus_ui_datakeys:/app/DataProtectionKeys


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - nexus.scheduler
      - nexus.integrator

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
    volumes:
      - grafana_data:/var/lib/grafana

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./loki/config.yml:/etc/loki/config.yml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      # - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - //./pipe/docker_engine://./pipe/docker_engine
      - ./promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

volumes:
  grafana_data:
  # nexus_ui_datakeys:  