auth_enabled: false
server:
  http_listen_port: 3100
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1m
  chunk_retain_period: 30s
  wal:
    enabled: false
schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb        # boltdb -> tsdb로 변경
      object_store: filesystem
      schema: v13        # v11 -> v13으로 변경
      index:
        prefix: index_
        period: 24h
storage_config:
  tsdb_shipper:          # boltdb -> tsdb_shipper로 변경
    active_index_directory: /loki/tsdb-index
    cache_location: /loki/tsdb-cache
  filesystem:
    directory: /loki/chunks
limits_config:
  allow_structured_metadata: true  # 최신 기능 활성화